### ISSUE TITLE
Workspace Setup

### ISSUE THREAD

**Issue by aarmijo** [denkbares/d3web-KnowWE#8]
Hi there,

I'm trying to set-up the project and there seems to be a problem in the deployment into tomcat. Could you, please, provide some hints on how to solve the dependencies.

I get this log:

feb 08, 2022 5:55:39 P. M. [JSPWiki] de.knowwe.core.Environment init
GRAVE: Invalid initialization of the wiki. This is caused by an invalid wiki plugin. Wiki is in unstable state. Please exit and correct before using the wiki.
java.lang.Error: Unresolved compilation problems:
The package javax.xml is accessible from more than one module: , java.xml
The package javax.xml.transform is accessible from more than one module: , java.xml
The package javax.xml.transform.stream is accessible from more than one module: , java.xml
The package javax.xml.validation is accessible from more than one module: , java.xml
The package javax.xml.validation is accessible from more than one module: , java.xml
The package javax.xml.validation is accessible from more than one module: , java.xml
The package org.xml.sax is accessible from more than one module: , java.xml
The package org.xml.sax is accessible from more than one module: , java.xml
Source cannot be resolved to a type
The method loadAsSource(WikiAttachment) from the type XMLValidationHandler refers to the missing type Source
Schema cannot be resolved to a type
SchemaFactory cannot be resolved to a type
SchemaFactory cannot be resolved
SAXException cannot be resolved to a type
Source cannot be resolved to a type

Thanks in advance.
Alberto

**Comment by AlbrechtStriffler** [comment]
You also openend a discussion-topic which is also a bit more fitting I think. I answered there: https://github.com/denkbares/d3web-KnowWE/discussions/7#discussioncomment-2135022

If there are follow-ups, lets have them over there and close this issue for now.
